version: '3'

services:
  docker-server-clswk:
    build:
      context: .
      target: deploy
    environment:
      - DATABASE_URL=jdbc:postgresql://cats-db-clswk:5432/postgres
      - SERVER_PORT=8090
    ports:
      - "8090:8090"
    depends_on:
      cats-db-clswk:
        condition: service_started
      
  cats-db-clswk:
    image: postgres:latest 
    environment:
      - ​​​​POSTGRES_DB=cats_db_clswk​​​​
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
